const { Connection, PublicKey, Transaction, SystemProgram, Keypair, LAMPORTS_PER_SOL, sendAndConfirmTransaction } = require('@solana/web3.js');
const bs58 = require('bs58');
const fs = require('fs');

const DEVNET_RPC = 'https://api.devnet.solana.com';

async function transferSol() {
    try {
        console.log('====================================');
        console.log('  Transfer SOL Between Wallets');
        console.log('====================================\n');

        const fromAddress = '438Fvd6tYJwgvCNC2Sk43kd46rVagKF7N8tcN9biZ9dj';
        const toAddress = 'CFzR4e6zrXLj2cvJKjGtvwLQP2is7swMYmCMPQTBbE6B';
        const amount = 5; // SOL to transfer

        console.log(`From: ${fromAddress}`);
        console.log(`To:   ${toAddress}`);
        console.log(`Amount: ${amount} SOL\n`);

        // Check if we have the private key for the OLD brand wallet
        console.log('❌ ERROR: Cannot transfer automatically!');
        console.log('\nThe old brand wallet (438Fvd6tYJwgvCNC2Sk43kd46rVagKF7N8tcN9biZ9dj)');
        console.log('was generated by a previous backend session that has been lost.');
        console.log('\nUnfortunately, without the private key of that wallet,');
        console.log('the 5 SOL is NOT accessible.\n');

        console.log('📝 SOLUTION:');
        console.log('You need to send NEW SOL to your current brand wallet:');
        console.log(`\nBrand Wallet: ${toAddress}`);
        console.log('\nOptions:');
        console.log('1. Request airdrop (devnet only):');
        console.log(`   solana airdrop 5 ${toAddress} --url devnet`);
        console.log('\n2. Send from your login wallet using Phantom or Solflare\n');
        console.log('\n3. OR - Let me request a devnet airdrop for you now...\n');

        console.log('====================================\n');

    } catch (error) {
        console.error('❌ Error:', error.message);
    }
}

transferSol();
